### ISSUE TITLE
Data simulator with Blender or Pyrender?

### ISSUE THREAD

**Issue by YuxuanSnow** [ligengen/EgoGen#3]
Hi,

I saw there is scripts to use `Pyrender` to generate RGB/depth from the random scene, body, and cloth, together with cloth simulation based on HOOD.

According to the paper, you use the `Blender` to simulate the data including RGB with motion blur, Depth with Kinect artefacts, Normal map and optical flow. Where I can find such a script to use `Blender` script and automatic simulate scene, body, cloth and generate these different data modalities?

**Comment by ligengen** [comment]
Hi,
Various rendering tools can be used for different objectives. To synthesize photorealistic data, Blender is a good choice. UE or Unity could also be leveraged. To render data with a fast speed, Pyrender is a good choice as in our HMR experiment. To render data in a huge scene (>5GB scene mesh), [Raybender](https://github.com/cvg/raybender) is leveraged as in our mapping and localization experiment. And you may try the `bpy` module.
